"""change my.cnf

Revision ID: 1d0688342a70
Revises: 9fda45c63f87
Create Date: 2022-12-23 11:34:15.766082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0688342a70'
down_revision = '9fda45c63f87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
