"""change slot to bid relation

Revision ID: 2055dac97367
Revises: 9a9afb9e5264
Create Date: 2023-02-10 13:36:21.546059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '2055dac97367'
down_revision = '9a9afb9e5264'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('slot_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True))
    op.create_foreign_key(None, 'bid', 'slot', ['slot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('slot_ibfk_1', 'slot', type_='foreignkey')
    op.drop_column('slot', 'bid_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('bid_id', mysql.CHAR(length=32), nullable=True))
    op.create_foreign_key('slot_ibfk_1', 'slot', 'bid', ['bid_id'], ['id'])
    op.drop_constraint(None, 'bid', type_='foreignkey')
    op.drop_column('bid', 'slot_id')
    # ### end Alembic commands ###
