"""add lacking relations

Revision ID: 48343c82a8d0
Revises: e78301da09ae
Create Date: 2022-12-23 09:38:18.851195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48343c82a8d0'
down_revision = 'e78301da09ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
