"""revise import statement

Revision ID: 73daf49b98f1
Revises: 891c5c30e536
Create Date: 2022-12-23 16:07:39.497110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73daf49b98f1'
down_revision = '891c5c30e536'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
