"""create bidder table

Revision ID: 745531812a97
Revises: 785cbdb959fd
Create Date: 2023-02-10 12:07:13.941111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '745531812a97'
down_revision = '785cbdb959fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidder',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False, comment='更新日時'),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('bid_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bid.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bid', sa.Column('open_time', sa.DateTime(), nullable=True))
    op.add_column('bid', sa.Column('close_time', sa.DateTime(), nullable=True))
    op.drop_constraint('bid_ibfk_1', 'bid', type_='foreignkey')
    op.drop_column('bid', 'lowest_user_id')
    op.drop_column('bid', 'lowest_point')
    op.drop_column('bid', 'second_point')
    op.drop_column('bid', 'start_time')
    op.drop_column('bid', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('end_time', mysql.DATETIME(), nullable=True))
    op.add_column('bid', sa.Column('start_time', mysql.DATETIME(), nullable=True))
    op.add_column('bid', sa.Column('second_point', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('bid', sa.Column('lowest_point', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('bid', sa.Column('lowest_user_id', mysql.CHAR(length=32), nullable=True))
    op.create_foreign_key('bid_ibfk_1', 'bid', 'user', ['lowest_user_id'], ['id'])
    op.drop_column('bid', 'close_time')
    op.drop_column('bid', 'open_time')
    op.drop_table('bidder')
    # ### end Alembic commands ###
