"""add ondelete to task,user model

Revision ID: 785cbdb959fd
Revises: b61fbab97c58
Create Date: 2023-02-08 11:16:20.741597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '785cbdb959fd'
down_revision = 'b61fbab97c58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp on update current_timestamp'), nullable=False, comment='更新日時'),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_table',
    sa.Column('template', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('slot', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.ForeignKeyConstraint(['slot'], ['slot.id'], ),
    sa.ForeignKeyConstraint(['template'], ['template.id'], ),
    sa.PrimaryKeyConstraint('template', 'slot')
    )
    op.drop_constraint('slot_ibfk_3', 'slot', type_='foreignkey')
    op.drop_constraint('slot_ibfk_2', 'slot', type_='foreignkey')
    op.create_foreign_key(None, 'slot', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'slot', 'user', ['creater_id'], ['id'], ondelete='SET NULL')
    op.add_column('task', sa.Column('max_woker_num', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('min_woker_num', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('exp_woker_num', sa.Integer(), nullable=True))
    op.drop_constraint('task_ibfk_1', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['creater_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_ibfk_1', 'task', 'user', ['creater_id'], ['id'])
    op.drop_column('task', 'exp_woker_num')
    op.drop_column('task', 'min_woker_num')
    op.drop_column('task', 'max_woker_num')
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.create_foreign_key('slot_ibfk_2', 'slot', 'user', ['creater_id'], ['id'])
    op.create_foreign_key('slot_ibfk_3', 'slot', 'task', ['task_id'], ['id'])
    op.drop_table('template_table')
    op.drop_table('template')
    # ### end Alembic commands ###
