"""wakaran

Revision ID: 891c5c30e536
Revises: 1d0688342a70
Create Date: 2022-12-23 11:52:27.711118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891c5c30e536'
down_revision = '1d0688342a70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
