"""check update

Revision ID: 916ff7a70842
Revises: 2055dac97367
Create Date: 2023-02-10 22:26:06.311119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916ff7a70842'
down_revision = '2055dac97367'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
