"""revise error of bidder

Revision ID: 9a9afb9e5264
Revises: dcbd14eba696
Create Date: 2023-02-10 12:38:06.685457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9afb9e5264'
down_revision = 'dcbd14eba696'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
