"""add task propety to tag

Revision ID: 9fda45c63f87
Revises: 48343c82a8d0
Create Date: 2022-12-23 09:42:53.742863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fda45c63f87'
down_revision = '48343c82a8d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
