"""revise import of models.py

Revision ID: a05a2f076a1b
Revises: 73daf49b98f1
Create Date: 2022-12-23 17:01:45.911765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05a2f076a1b'
down_revision = '73daf49b98f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
