"""check whether error occur

Revision ID: b61fbab97c58
Revises: 4291eb2e2188
Create Date: 2022-12-30 13:32:53.436669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61fbab97c58'
down_revision = '4291eb2e2188'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
