"""add creater column in slot and task

Revision ID: b84df37812bf
Revises: 32a14792b6a8
Create Date: 2022-12-22 10:26:46.426839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84df37812bf'
down_revision = '32a14792b6a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
