"""revise error

Revision ID: dcbd14eba696
Revises: a5a876c62dff
Create Date: 2023-02-10 12:35:06.530342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbd14eba696'
down_revision = 'a5a876c62dff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
