"""add user column to achivement

Revision ID: e78301da09ae
Revises: b84df37812bf
Create Date: 2022-12-23 00:34:12.408917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78301da09ae'
down_revision = 'b84df37812bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
